"""share_image.py — shareable 1080x1080 result card (PIL, no streamlit needed).

make_share_image(village, risk_pct, band, date_str) -> BytesIO (PNG).
Band: 'Low' | 'Moderate' | 'High'. Never raises for bad input — falls back
to safe defaults. Urdu lines render only if an Arabic-capable font is found;
otherwise they are skipped gracefully (image stays English-only).
"""

import io
import os
from datetime import date

from PIL import Image, ImageDraw, ImageFont

SIZE = 1080

BAND_STYLE = {
    "Low": {"color": (46, 204, 113), "ur": "کم خطرہ"},
    "Moderate": {"color": (241, 196, 15), "ur": "درمیانہ خطرہ"},
    "High": {"color": (231, 76, 60), "ur": "زیادہ خطرہ"},
}

_FONT_CANDIDATES = {
    "latin_bold": [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    ],
    "latin": [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ],
    "urdu": [
        "/usr/share/fonts/truetype/noto/NotoKufiArabic-Bold.ttf",
        "/usr/share/fonts/truetype/noto/NotoSansArabic-ExtraCondensedSemiBold.ttf",
    ],
}


def _load(kind, size):
    for p in _FONT_CANDIDATES[kind]:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                continue
    return ImageFont.load_default()


def _gradient(size, top=(11, 37, 69), bottom=(4, 14, 28)):
    img = Image.new("RGB", (size, size), top)
    px = img.load()
    for y in range(size):
        t = y / (size - 1)
        c = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3))
        for x in range(size):
            px[x, y] = c
    return img


def _center(draw, y, text, font, fill):
    box = draw.textbbox((0, 0), text, font=font)
    w = box[2] - box[0]
    draw.text(((SIZE - w) / 2 - box[0], y), text, font=font, fill=fill)
    return y + (box[3] - box[1])


def make_share_image(village, risk_pct, band, date_str=None):
    """Build the share card. Returns BytesIO with PNG data."""
    band = band if band in BAND_STYLE else "Moderate"
    try:
        pct = float(risk_pct)
    except Exception:
        pct = 0.0
    pct = max(0.0, min(100.0, pct))
    style = BAND_STYLE[band]
    if date_str is None:
        date_str = date.today().isoformat()

    img = _gradient(SIZE)
    d = ImageDraw.Draw(img)

    f_title = _load("latin_bold", 64)
    f_big = _load("latin_bold", 170)
    f_sub = _load("latin", 44)
    f_band = _load("latin_bold", 72)
    f_small = _load("latin", 34)
    f_urdu = _load("urdu", 56)

    y = 90
    y = _center(d, y, "FloodGuard AI", f_title, (255, 255, 255)) + 18
    y = _center(d, y, "Flood Risk Report  |  Pakistan", f_small,
                (160, 190, 220)) + 40

    # colored band stripe
    d.rectangle([140, y, SIZE - 140, y + 10], fill=style["color"])
    y += 50

    y = _center(d, y, f"{pct:.1f}%", f_big, style["color"]) + 45
    y = _center(d, y, f"{band} Risk", f_band, (255, 255, 255)) + 14

    # Urdu band label (only if a real Arabic font loaded)
    if getattr(f_urdu, "path", ""):
        y = _center(d, y, style["ur"], f_urdu, (200, 210, 225)) + 24
    else:
        y += 10

    y = _center(d, y, str(village)[:48], f_sub, (235, 240, 248)) + 12
    y = _center(d, y, date_str, f_small, (150, 175, 200)) + 60

    # footer disclaimer
    d.rectangle([0, SIZE - 150, SIZE, SIZE], fill=(3, 10, 20))
    _center(d, SIZE - 120,
            "Not for emergency use - follow official PDMA / NDMA alerts.",
            f_small, (140, 160, 180))
    _center(d, SIZE - 70, "Generated by FloodGuard AI", f_small,
            (110, 135, 160))

    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf
